name: Build and Deploy
on: 
  push:
    branches: [master]

jobs: 
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy python bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd /var/www/pb_class_theory
            git pull
            docker build -t pb_class_theory .
            docker rm -f pb_class_theory
            docker run -d --env-file .env --name pb_class_theory --network network_local pb_class_theory
            
            
